version: '3.8'

services:
  app:
    build: .
    container_name: newsbite_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://db:27017/news_summarizer
      - JWT_SECRET=${JWT_SECRET}
      - NEWS_API_KEY=${NEWS_API_KEY}
      - CLIENT_ORIGIN=${CLIENT_ORIGIN}
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
      - ./logs:/app/logs
      - ./assets:/app/assets

  db:
    image: mongo:latest
    container_name: newsbite_db
    restart: always
    ports:
      - "27017:27017" # Exposed for local tool access, can be removed in production
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
